language: c++
sudo: false

matrix:
  include:
    # GCC 6
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
            - cmake
          sources:
            - ubuntu-toolchain-r-test
      env: COMPILER=g++-6

    # Clang 3.9
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - cmake
          sources:
            - ubuntu-toolchain-r-test
      env: LLVM_VERSION=3.9.0

install:
  - cmake . -Bbuild
  - cmake --build build

scripts:
  - ./build/test/test_sdptransform

notifications:
  email:
    recipients:
      - ibc@aliax.net
    on_success: change
    on_failure: always
